<a href="https://colab.research.google.com/github/putrinahampun/StartupCampusJourney/blob/main/PythonFoundation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello World!")

Hello World!


### Library yang digunakan untuk analisa data, yaitu:

1.   Numpy => untuk pengerjaan fungsi yang bersifat numerik
2.   Pandas => untuk visualisasi data dalam bentuk tabel (tabular), untuk manipulasi data
3.   Matplotlib dan Seaborn => visualisasi data dalam bentuk grafik dari hasil olahan data pada pandas.
4.   Scikit-learn => melatih model machine learning dengan menggunakan data
5.   Tensorflow => framework ML yang dikembangkan Google untuk melatih model ML dan banyak digunakan untuk Deep Learning / Image Recognition.
6.   Keras => Library untuk aplikasi Neural Network.
7.   PyTorch => algoritma ML yang digunakan untuk melatih model Neural Network.   



In [3]:
nama = "Startup Campus"
print(nama)

Startup Campus


In [4]:
print("startup"); print("campus")

startup
campus


In [5]:
nama = "putri"; age = 10 # nama dan age merupakan variabel yang menyimpan value

In [6]:
print(nama); print(age)

putri
10


### Beberapa Tipe Data, yaitu:

1.   List => menyimpan berbagai tipe data yang isinya bisa diubah-ubah
2.   Tuple => menyimpan tipe data yang isinya tidak dapat diubah
3.   Dictionary => menyimpan tipe data sebagai sebuah pasangan 'key' 'value', bersifat runut, bisa diubah, dan unik.
4.   Set => tidak bisa diubah, namun bisa dipanggil dengan index.




In [7]:
# TIPE DATA
x = 5 #integer
x = 0.5 #float
x = 3j #complex
x = 'putri' #string
x = ['satu','dua','tiga'] #list
x = ('satu','dua','tiga') #tuple
x = {'satu':1,'dua':2,'tiga':3} #dictionary
x = True #boolean
x = None #nonetype

In [8]:
price = 100000
satuan = 'rupiah'

print("Harga Barang:",price,satuan)

Harga Barang: 100000 rupiah


### Module dan Package Python

1.   Module => kumpulan dari fungsi custom yang dibuat sendiri oleh programmer.
2.   Package => mirip dengan module, namun package bersifat general-used. Cth: Numpy, Pandas.
3.   Cara instalasi Package di python: !pip install <package_name> (untuk google colab).
4.   Cara instalasi Package di IDE:
pip install <package_name>



### Arithmetics Operators Python

*   tambah (+)
*   kurang (-)
*   bagi (/)
*   kali (*)
*   sisa bagi (%)
*   pangkat (**)
*   pembulatan (//)


In [9]:
# KONDISI IF
a = 5
b = 100
if b > a:
  print("b lebih besar dari a ")

b lebih besar dari a 


In [10]:
# KONDISI IF ELIF
a = 90
b = 50
if b > a:
  print('b lebih besar dari a')
elif a == b:
  print("a dan b memiliki nilai yang sama")
else:
  print("a lebih besar dari b")

a lebih besar dari b


In [11]:
# KONDISI NESTED IF
a = 50
b = 60
if b > a:
  print('b lebih besar dari a')
  if b % 2 == 0:
    print("b adalah bilangan genap")
elif a == b:
  print("a dan b memiliki nilai yang sama")
else:
  print("a lebih besar dari b")

b lebih besar dari a
b adalah bilangan genap


### Pengulangan (LOOP) ada 2, yaitu:

1.   while Loop => melakukan iterasi selama kondisi dinyatakan benar.
2.   For Loop => define iteration



In [12]:
# LOOP => PENGULANGAN

# While Loop
i = 1
while i < 6:
  print(i, end=" ")
  i += 1


1 2 3 4 5 

In [13]:
# For Loop
for x in "banana":
  print(x)

b
a
n
a
n
a


In [14]:
for x in range(1,6):
  print(x)

1
2
3
4
5


In [15]:
for x in range(1,6,2):
  print(x)

1
3
5


### Fungsi pada Loop:

1.   Break => memberhentikan proses loop
2.   Continue => melewatkan satu putaran loop
3.   Pass => mengisi fungsi loop yang kosong



In [16]:
# break
for i in range(1,5):
  if i == 3:
    break
  else:
    print(i)

1
2


In [17]:
# continue
for i in range(1,5):
  if i % 2 == 0:
    continue
  else:
    print(i)

1
3


In [18]:
# pass
for i in range(10):
  pass

In [19]:
# NESTED LOOP
for x in "banana":
  for y in range(6):
    print(x, end=" ")
  print("")
print("end of code")

b b b b b b 
a a a a a a 
n n n n n n 
a a a a a a 
n n n n n n 
a a a a a a 
end of code


In [20]:
# FUNGSI
def grade(point):
  if point > 90:
    status = 'You got A!'
  elif point >=70 and point <=90:
    status = "You got B!"
  else:
    status = "You got C!"
  return status

In [21]:
grade(100)

'You got A!'

In [22]:
grade(80)

'You got B!'

In [23]:
grade(60)

'You got C!'

### Jenis Input pada Function

1.   Positional Arguments => perhatikan posisinya, general digunakan
2.   Keyword Arguments => posisi tidak masalah, mudah mengenali inputnya
3.   Default Arguments => gabungan positional dan keyword
4.   Variable-Length Arguments => menggunakan operator *args dan **kwargs
    * (*args) => input dianggap list
    * (**kwargs) => seluruh input merupakan arguments, bisa beda jenis tipe data.
    *  penggabungan *args,**kwargs,dan positional arguments



In [24]:
#  positional arguments
def penjumlahan(a,b):
  print("Ini nilai b:",b)
  print("Ini nilai a:",a)
  c = a + b
  return c

penjumlahan(2,3)

Ini nilai b: 3
Ini nilai a: 2


5

In [25]:
# keyword arguments
def penjumlahan(a,b):
  print("Ini nilai b:",b)
  print("Ini nilai a:",a)
  c = a + b
  return c

penjumlahan(b = 4, a = 6)

Ini nilai b: 4
Ini nilai a: 6


10

In [26]:
# default arguments
def penjumlahan(a,b=10):
  print("Ini nilai b:",b)
  print("Ini nilai a:",a)
  c = a + b
  return c

penjumlahan(a = 6)
penjumlahan(9,b=21)

Ini nilai b: 10
Ini nilai a: 6
Ini nilai b: 21
Ini nilai a: 9


30

In [27]:
#  *args arguments
def penjumlahann(*args):
  return print(sum(args))

def pengurangan(*args):
  start = args[0]
  for x in args[1:]:
    start -= x
  return print(start)

penjumlahann(10,20,30)
pengurangan(100,20,30)

60
50


In [28]:
# **kwargs arguments
def biodata(**kwargs):
  for key,value in kwargs.items():
    print("{} is {}".format(key,value))

biodata(nama ="putri", usia=20, pekerjaan='mahasiswa')

nama is putri
usia is 20
pekerjaan is mahasiswa


In [29]:
# penggabungan *args, **kwargs, positional arguments
def biodatta(nim,nama,*args,**kwargs):
  print("nim : {}".format(nim))
  print("nama: {}".format(nama))
  print("jurusan: {}".format(args[0]))
  print("universitas: {}".format(args[1]))

  for x,y in kwargs.items():
    print("{} : {}".format(x,y))

biodatta(201402061, "Putri", "Teknologi Informasi","Universitas Sumatera Utara",
         Hobi= "Membaca", Idola= "Haechan")

nim : 201402061
nama: Putri
jurusan: Teknologi Informasi
universitas: Universitas Sumatera Utara
Hobi : Membaca
Idola : Haechan


### Tipe variabel ada 2, yaitu:

1.   Variabel Lokal => berada didalam fungsi/module tertentu
2.   Variabel Global => bisa diakses keseluruhan codes.



In [30]:
# Global dan Lokal Variabel

x = 10 #variabel global

def penambahan():
  x = 15 #varibael lokal
  y = 20
  print("nilai x:{}".format(x))
  print("nilai y:{}".format(y))

penambahan()
print(x)

nilai x:15
nilai y:20
10


In [31]:
# LIBRARY PADA PYTHON

# memanggil library NUMPY
import numpy as np

# memanggil library pandas
import pandas as pd


### Pembahasan tentang Numpy:

1.   Numpy (Numerical Python) => library yang digunakan dalam pembuatan array, dibuat Travis Oliphant, merupakan salah satu contoh proyek Open source.
2.   Kelebihan:
  * lebih cepat dari List
  * menggunakan lebih sedikit memori
  * bisa digunakan untuk membuat array n-dimensi
  * bisa melalukan operasi matematika pada array n-dimensi.
3.   Objek array pada numpy disebut ndarray (nth-dimmesion array).
4.   Pembuatan ndarray menggunakan fungsi array().
  * array 1 dimensi (1D array): mengolah angka
  * array 2 dimensi (2D array): mengolah gambar
  * array 3 dimensi (3D array): mengolah gambar RGB.
5. numpy menciptakan sebuah array disebut dengan matriks.
6. numpy berhubungan dengan operasi vektor (dot product, cross product, inverse).



In [32]:
# 1D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [33]:
# 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [34]:
# 3D array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print("\n")
print("jumlah dimensi array {}".format(arr.ndim)) # menampilkan jumlah dimensi pada array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


jumlah dimensi array 3


In [35]:
# Pemanggilan Array 1D
arrcheck = np.array([1,2,3,4,5])
print(arrcheck[3])
print(arrcheck[0] + arrcheck[3])

4
5


In [36]:
# Pemanggilan Array 2D
arnold = np.array([[1,2,3],[4,5,6]])
print(arnold[0][1])

2


In [37]:
# Pemanggilan Array 3D
jesse = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(jesse[0][1][1])

5


In [38]:
# Pengubahan nilai array
jessica = np.array([[1,2,3],[4,5,6]])
print("Sebelum pengubahan:{}".format(jessica))
jessica[1][0] = 10
print("Sesudah pengubahan:{}".format(jessica))


Sebelum pengubahan:[[1 2 3]
 [4 5 6]]
Sesudah pengubahan:[[ 1  2  3]
 [10  5  6]]


In [39]:
# SLICING => PENGAMBILAN BEBERAPA NILAI ITEM PADA ARRAY
# slicing 1D array
number = np.array([1,2,3,4,5])
print(number[1:3])

[2 3]


In [40]:
# slicing 2D array
number2 = np.array([[1,2,3],[4,5,6]])
print(number2[0,:])

[1 2 3]


In [41]:
# slicing 3D array
number3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(number3[1,1,:])

[10 11 12]


### Nilai dalam array dapat diubah dengan menggunakan fungsi astype() dan argument karakter berikut:

*   integer (i)
*   boolean (b)
*   unsigned integer (u)
*   float (f)
*   object (o)
*   string (s)



In [42]:
# MENGUBAH TIPE DATA ARRAY
arra = np.array(['1','2','3'])
newArra = arra.astype('i')
print(newArra)

[1 2 3]


In [43]:
# PENGUBAHAN DIMENSI ARRAY DENGAN MENGGUNAKNA FUNGSI RESHAPE()
# 1D array -> 2d array
check = np.array([1,2,3,4,5,6])
new_check = check.reshape(2,3) #arugment pada fungsi reshape kalo dikalikan harus memiliki nilai yang sama dengan jumlah item pada array
new_check

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# 2d array -> 3d array
check2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_check2 = check2.reshape(2,3,2)
new_check2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [45]:
# REDUKSI DIMENSI ARRAY (2D array -> 1D array)
tes = np.array([[1,2,3],[4,5,6]])
new_tes = tes.reshape(-1)
new_tes

array([1, 2, 3, 4, 5, 6])

In [46]:
# ITERASI ARRAY

# 1D array
arrayy = np.array([1,2,3,4,5])
for x in arrayy:
  print(x)

1
2
3
4
5


In [47]:
# 2D array
arrayy2 = np.array([[1,2,3],[4,5,6]])
for x in arrayy2:
  for y in x:
    print(y)

1
2
3
4
5
6


In [48]:
# 3D array
arrayy3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arrayy3:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Penggunaan Array Join, yaitu:

*   menggabungkan dua buah array. tidak sama dengan implementasi penjumlahan string.
*   menggunakan concatenate()
*   axis = 0, maka membentuk baris baru (default)
*   axis = 1, maka membentuk kolom baru




In [49]:
# Array concat

arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[5,6,7,8,9]])

arrtot = np.concatenate((arr1,arr2),axis = 0)
print(arrtot)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [50]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[5,6,7,8,9]])

arrtot = np.concatenate((arr1,arr2),axis = 1)
print(arrtot)

[[1 2 3 4 5 5 6 7 8 9]]


In [51]:
# ARRAY SPLITTING

start = np.array([1,2,3,4,5,6])
new_start = np.array_split(start,3)

print("Sebelum:{}".format(start))
print("Sesudah:{}".format(new_start))

Sebelum:[1 2 3 4 5 6]
Sesudah:[array([1, 2]), array([3, 4]), array([5, 6])]


In [52]:
old = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
new = np.array_split(old,3)

print("Sebelum:{}".format(old))
print("Sesudah:{}".format(new))

Sebelum:[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Sesudah:[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [53]:
# ARRAY SEARCH => pencarian item dengan hasil index

old1 = np.array([1,2,3,4,5])
x = np.where(old1 == 1)
print(x)

(array([0]),)


In [54]:
y = np.where(old1 % 2 == 0)
print(y)

(array([1, 3]),)


In [55]:
z = np.where(old1 == 0)
print(z)

(array([], dtype=int64),)


In [56]:
# ARRAY SORT => mengurutkan

no_sort = np.array([5,3,2,1,4])
print(np.sort(no_sort))

[1 2 3 4 5]


In [57]:
no_sort2 = np.array([[2,3,1],[5,1,0]])
print(np.sort(no_sort2))

[[1 2 3]
 [0 1 5]]


In [58]:
alphabet = np.array(['cutipie','apple','banana'])
print(np.sort(alphabet))

['apple' 'banana' 'cutipie']


In [59]:
# REVERSED ARRAY => membalikkan urutan array

tes = np.array([3,2,1,4,5])
new_tes = np.sort(tes)

# reversed
re_tes = new_tes[::-1]

print("Sebelum:{}".format(new_tes))
print("Sesudah:{}".format(re_tes))

Sebelum:[1 2 3 4 5]
Sesudah:[5 4 3 2 1]


In [60]:
# OPERASI MATEMATIKA ARRAY

# penjumlahan  => konsep nya sama dengan pengurangan, pembagian, perkalian.
a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [61]:
 b = np.array([3,4,5,6])
 a + b

array([ 4,  6,  8, 10])

In [62]:
# OPERASI LOGIKA DALAM ARRAY
c = np.array([1,2,3,4,5])
d = np.array([5,4,3,2,1])

c == d

array([False, False,  True, False, False])

In [63]:
c > d

array([False, False, False,  True,  True])

In [64]:
np.array_equal(c,d)

False

In [65]:
# OPERASI VEKTOR DALAM ARRAY

# DOT PRODUCT 1D
e = np.array([1,2,3,4])
f = np.array([2,3,4,5])

np.dot(e,f)

40

In [66]:
# DOT PRODUCT 2D
g = np.array([[1,2,3],[4,5,6]])
h = np.array([2,3,4])

np.dot(g,h)

array([20, 47])

In [67]:
# CROSS PRODUCT

i = np.array([1,3])
j = np.array([2,4])

np.cross(i,j)

array(-2)

In [68]:
# PERKALIAN MATRIKS
a = np.array([[1,1],[1,2]])
b = np.array([[1,3],[2,4]])

np.matmul(a,b)

array([[ 3,  7],
       [ 5, 11]])

In [69]:
# INVERSE MATRIKS
a = np.array([[1,3],[2,4]])
a_inverse = np.linalg.inv(a)

a_inverse


array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [71]:
# untuk mengecek apakah nilai inverse benar atau tidak
np.matmul(a,a_inverse)

array([[1., 0.],
       [0., 1.]])

In [73]:
# TRANSPOSE MATRIKS

a = np.array([[1,3],[2,4]])
a.T

array([[1, 2],
       [3, 4]])

### PANDAS

1.   Pandas => library yang bersifat open-source. Banyak digunakan untuk manipulasi dan analisa data.
2.   Struktur data nya objek dataframe, sehingga mendukung pengindeksan (sehingga mudah untuk menemukan lokasi data).
3.   Pandas memungkinkan untuk membaca data dalam format CSV/text file, Microsoft Excel. databse SQL, format HDF5 (dengan menggunakan koneksi tertentu). Pandas memudahkan untuk reshaping dan pivoting.
4.   Dua jenis struktur data yang dapat diolah dengan Pandas:
   * series: array 1D yang menampung banyak jenis tipe data. (dibayangkan seperti 1 buah kolom)
   * dataframe: array 2D yang menampung banyak tipe data. (dibayangkan seperti baris dan kolom).



In [75]:
import pandas as pd

data = {
    'name' : ['putri','della','irma'],
    'id'   : ['201402061','201402151','201402136'],
    'age'  : [20,21,20],
    'major': ['TI','ILKOM','TI']
}

df = pd.DataFrame(data)
print(df)

    name         id  age  major
0  putri  201402061   20     TI
1  della  201402151   21  ILKOM
2   irma  201402136   20     TI


In [76]:
# membuat dataframe dari List
import pandas as pd

firstname = ['putri','della','irma']
lastname = ['yanti','febriana','ginting']

df = pd.DataFrame(list(zip(firstname,lastname)), columns = ['Firstname','Lastname'])
df

Firstname  Lastname
0     putri     yanti
1     della  febriana
2      irma   ginting

In [78]:
# membuat dataframe dari tuple
import pandas as pd

firstname = tuple(['putri','della','irma'])
lastname = tuple(['yanti','febriana','ginting'])

df = pd.DataFrame(list(zip(firstname,lastname)), columns =['Firstname','Lastname'])
df


Firstname  Lastname
0     putri     yanti
1     della  febriana
2      irma   ginting

In [79]:
# membuat dataframe dari dictionary
import pandas as pd

name = {'firstname':['putri','della','irma'],'lastname':['yanti','febriana','ginting']}

df = pd.DataFrame(name)
df

firstname  lastname
0     putri     yanti
1     della  febriana
2      irma   ginting

In [81]:
# membuat dataframe dari numpy array

import pandas as pd
import numpy as np

name = np.array([['putri','yanti'],['della','febriana'],['irma','ginting']])

df = pd.DataFrame(name, columns=['firstname','lastname'])
df

firstname  lastname
0     putri     yanti
1     della  febriana
2      irma   ginting